# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChaveValor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x43haveValor.proto\":\n\x06Pedido\x12\r\n\x05\x63have\x18\x01 \x01(\x05\x12\r\n\x05valor\x18\x02 \x01(\t\x12\x12\n\nid_servico\x18\x03 \x01(\t\"\"\n\x10RespostaInsercao\x12\x0e\n\x06status\x18\x01 \x01(\x05\"!\n\x10RespostaConsulta\x12\r\n\x05valor\x18\x01 \x01(\t\"\"\n\x10RespostaAtivacao\x12\x0e\n\x06status\x18\x01 \x01(\x05\"!\n\x0fRespostaTermino\x12\x0e\n\x06status\x18\x01 \x01(\x05\"(\n\x10RespostaRegistro\x12\x14\n\x0cnumeroChaves\x18\x01 \x01(\x05\"!\n\x0bRespostaMap\x12\x12\n\nid_servico\x18\x01 \x01(\t\"\x1a\n\tPedidoMap\x12\r\n\x05\x63have\x18\x01 \x01(\x05\"9\n\x0ePedidoRegistro\x12\x12\n\nid_servico\x18\x01 \x01(\t\x12\x13\n\x0bListaChaves\x18\x02 \x03(\x05\x32\xb2\x01\n\nChaveValor\x12(\n\x08Insercao\x12\x07.Pedido\x1a\x11.RespostaInsercao\"\x00\x12(\n\x08\x43onsulta\x12\x07.Pedido\x1a\x11.RespostaConsulta\"\x00\x12(\n\x08\x41tivacao\x12\x07.Pedido\x1a\x11.RespostaAtivacao\"\x00\x12&\n\x07Termino\x12\x07.Pedido\x1a\x10.RespostaTermino\"\x00\x32\x92\x01\n\x0fServidorCentral\x12\x30\n\x08Registro\x12\x0f.PedidoRegistro\x1a\x11.RespostaRegistro\"\x00\x12%\n\nMapeamento\x12\x07.Pedido\x1a\x0c.RespostaMap\"\x00\x12&\n\x07Termino\x12\x07.Pedido\x1a\x10.RespostaTermino\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChaveValor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PEDIDO']._serialized_start=20
  _globals['_PEDIDO']._serialized_end=78
  _globals['_RESPOSTAINSERCAO']._serialized_start=80
  _globals['_RESPOSTAINSERCAO']._serialized_end=114
  _globals['_RESPOSTACONSULTA']._serialized_start=116
  _globals['_RESPOSTACONSULTA']._serialized_end=149
  _globals['_RESPOSTAATIVACAO']._serialized_start=151
  _globals['_RESPOSTAATIVACAO']._serialized_end=185
  _globals['_RESPOSTATERMINO']._serialized_start=187
  _globals['_RESPOSTATERMINO']._serialized_end=220
  _globals['_RESPOSTAREGISTRO']._serialized_start=222
  _globals['_RESPOSTAREGISTRO']._serialized_end=262
  _globals['_RESPOSTAMAP']._serialized_start=264
  _globals['_RESPOSTAMAP']._serialized_end=297
  _globals['_PEDIDOMAP']._serialized_start=299
  _globals['_PEDIDOMAP']._serialized_end=325
  _globals['_PEDIDOREGISTRO']._serialized_start=327
  _globals['_PEDIDOREGISTRO']._serialized_end=384
  _globals['_CHAVEVALOR']._serialized_start=387
  _globals['_CHAVEVALOR']._serialized_end=565
  _globals['_SERVIDORCENTRAL']._serialized_start=568
  _globals['_SERVIDORCENTRAL']._serialized_end=714
# @@protoc_insertion_point(module_scope)
