# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Servicos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eServicos.proto\":\n\x06Pedido\x12\r\n\x05\x63have\x18\x01 \x01(\x05\x12\r\n\x05valor\x18\x02 \x01(\t\x12\x12\n\nid_servico\x18\x03 \x01(\t\"\"\n\x10RespostaInsercao\x12\x0e\n\x06status\x18\x01 \x01(\x05\"!\n\x10RespostaConsulta\x12\r\n\x05valor\x18\x01 \x01(\t\"\"\n\x10RespostaAtivacao\x12\x0e\n\x06status\x18\x01 \x01(\x05\"!\n\x0fRespostaTermino\x12\x0e\n\x06status\x18\x01 \x01(\x05\"(\n\x10RespostaRegistro\x12\x14\n\x0cnumeroChaves\x18\x01 \x01(\x05\"!\n\x0bRespostaMap\x12\x12\n\nid_servico\x18\x01 \x01(\t\"9\n\x0ePedidoRegistro\x12\x12\n\nid_servico\x18\x01 \x01(\t\x12\x13\n\x0bListaChaves\x18\x02 \x03(\x05\x32\xb2\x01\n\nChaveValor\x12(\n\x08Insercao\x12\x07.Pedido\x1a\x11.RespostaInsercao\"\x00\x12(\n\x08\x43onsulta\x12\x07.Pedido\x1a\x11.RespostaConsulta\"\x00\x12(\n\x08\x41tivacao\x12\x07.Pedido\x1a\x11.RespostaAtivacao\"\x00\x12&\n\x07Termino\x12\x07.Pedido\x1a\x10.RespostaTermino\"\x00\x32\x92\x01\n\x0fServidorCentral\x12\x30\n\x08Registro\x12\x0f.PedidoRegistro\x1a\x11.RespostaRegistro\"\x00\x12%\n\nMapeamento\x12\x07.Pedido\x1a\x0c.RespostaMap\"\x00\x12&\n\x07Termino\x12\x07.Pedido\x1a\x10.RespostaTermino\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Servicos_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PEDIDO']._serialized_start=18
  _globals['_PEDIDO']._serialized_end=76
  _globals['_RESPOSTAINSERCAO']._serialized_start=78
  _globals['_RESPOSTAINSERCAO']._serialized_end=112
  _globals['_RESPOSTACONSULTA']._serialized_start=114
  _globals['_RESPOSTACONSULTA']._serialized_end=147
  _globals['_RESPOSTAATIVACAO']._serialized_start=149
  _globals['_RESPOSTAATIVACAO']._serialized_end=183
  _globals['_RESPOSTATERMINO']._serialized_start=185
  _globals['_RESPOSTATERMINO']._serialized_end=218
  _globals['_RESPOSTAREGISTRO']._serialized_start=220
  _globals['_RESPOSTAREGISTRO']._serialized_end=260
  _globals['_RESPOSTAMAP']._serialized_start=262
  _globals['_RESPOSTAMAP']._serialized_end=295
  _globals['_PEDIDOREGISTRO']._serialized_start=297
  _globals['_PEDIDOREGISTRO']._serialized_end=354
  _globals['_CHAVEVALOR']._serialized_start=357
  _globals['_CHAVEVALOR']._serialized_end=535
  _globals['_SERVIDORCENTRAL']._serialized_start=538
  _globals['_SERVIDORCENTRAL']._serialized_end=684
# @@protoc_insertion_point(module_scope)
